# Generated by Django 3.2.7 on 2021-11-01 14:35

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0002_auto_20211101_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdata',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 20, 5, 4, 873484)),
        ),
        migrations.AlterField(
            model_name='blogdata',
            name='student',
            field=models.ForeignKey(default='anonymous', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
