# Generated by Django 3.2.7 on 2021-11-01 15:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20211101_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdata',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 20, 33, 7, 852150)),
        ),
    ]
