# Generated by Django 3.2.7 on 2021-11-01 16:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_alter_blogdata_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdata',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 1, 21, 53, 26, 42036)),
        ),
        migrations.AlterField(
            model_name='blogdata',
            name='img',
            field=models.ImageField(default='/static/default_user.jpg', upload_to='pics'),
        ),
    ]
