# Generated by Django 3.2.7 on 2021-11-06 07:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20211102_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogdata',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 6, 12, 46, 35, 48587)),
        ),
        migrations.AlterField(
            model_name='blogdata',
            name='title',
            field=models.CharField(max_length=150),
        ),
    ]
